### ISSUE TITLE
CMMD dataset

### ISSUE THREAD

**Issue by Ch1kara** [nyukat/mammography_metarepository#14]
Hi,

I am wondering how did you divide the train/test/validation for the CMMD dataset. Is there any file list that you can provide?

Cheers

**Comment by jwitos** [comment]
Hi @Ch1kara, thanks for your question! We used full CMMD dataset for evaluation, i.e. all 1,775 studies. This is a relatively new dataset so none of the models in the meta-repository were trained using CMMD data. Please refer to the TCIA website for CMMD dataset details/download: https://wiki.cancerimagingarchive.net/pages/viewpage.action?pageId=70230508.

**Comment by Ch1kara** [comment]
Thank you so much for your explanation!

**Comment by Ch1kara** [comment]
Hi Jwitos,

I am wondering if it's possible for you to share the data.pkl generator file for CMMD dataset?

Cheers
