### ISSUE TITLE
VOI LUT functions

### ISSUE THREAD

**Issue by Ch1kara** [nyukat/mammography_metarepository#16]
Hi 

I am wondering did you use the apply_voi_lut function for the DICOM file on CMMD?

Cheers

**Comment by jwitos** [comment]
Hi @Ch1kara, first of all sorry for late reply. I've had a bunch of other time sensitive projects. I'll do my best to reply to your tickets as soon as possible.
Regarding this question, I believe that we did not apply this for CMMD DICOM files. Note that those DICOMs have `(0008, 0068) Presentation Intent Type` tag value set to `FOR PRESENTATION`. To my understanding, this means that all grayscale transformations including VOI LUT have already been applied (see [C.8.11.1.1.1 of DICOM Standard](http://dicom.nema.org/medical/dicom/current/output/chtml/part03/sect_C.8.11.html)).

**Comment by Ch1kara** [comment]
Thank you for the comment!
