### ISSUE TITLE
Pre-processing method

### ISSUE THREAD

**Issue by Ch1kara** [nyukat/mammography_metarepository#20]
Hi Guys, 

When I am testing the pre-processing algorithm on my dataset I found that in some cases the MLO mammograms are not well-repersented. Just wondering have you guys considered how to avoid these cases?

Cheers
![Screenshot from 2021-12-05 18-03-53](https://user-images.githubusercontent.com/57159401/144738005-c9e58353-eda5-408c-b5c4-d81c7662e032.png)

**Comment by chledowski** [comment]
Hi!

Could you give some details, i.e. which images have this problem?

**Comment by Ch1kara** [comment]
A few MLO images in my dataset

**Comment by chledowski** [comment]
Hi.

Looks like there might be several problems with these images:
1) Having a strictly 0-value background is a must for our algorithm to work - seems like the background is not strictly 0 on those images.
2) The images are possibly too large - you might need to either downscale the original image or use a bigger cropping window.
3) The number of iterations in morphological operations must increase depending on whether you downscaled the original image or used a bigger cropping window - `--num-iterations` parameter in https://github.com/nyukat/GMIC/blob/master/src/cropping/crop_mammogram.py. The morphological operations should get rid of occasional artifacts in the background as well as stomach, but the default value won't be enough for images with higher resolutions.


We will discuss adjusting the preprocessing pipeline to work in such cases.

**Comment by jwitos** [comment]
I'll just add that it would be easier for us to troubleshoot if you could share at least a de-identified original DICOM(s) so that we can have a minimal, complete reproducible example. Without it we can make a few guesses as you can see above but it's difficult to find the ultimate problem

**Comment by Ch1kara** [comment]
Hi @jwitos and @chledowski 
Thanks for reaching out, I am afraid I cannot send you guys the de-identified DICOM files. I neither have the access to the original files nor have the permission to do. I guess I would just follow the advice suggested by @chledowski. 
Thank you guys so much!
