### ISSUE TITLE
Preprocess CBIS-DDSM images before running GMIC

### ISSUE THREAD

**Issue by HongjianLi** [nyukat/mammography_metarepository#28]
Hi. I'm using this metarepository, especially the GMIC docker, to run GMIC on CBIS-DDSM images. I'm concerned about the preprocessing procedure.

The GMIC paper mentions four proprocessing steps: "To preprocess mammography images in CBIS-DDSM,
* we first found the largest connected component containing only non-zero pixels to locate the breast.
* We then applied erosion and dilation to refine the breast margin.
* Lastly, we re-oriented all mammography images so that the breasts are always on the left side of the image. 
* All images are resized to 2944 × 1920 pixels and pixels values were normalized to the range [0,1]."

I wonder if these four preprocessing steps are already included in the GMIC scripts, or do I have to write code to implement them?

I've checked out the GMIC repository and found a script named run.sh, which executes three other scripts:
* crop_mammogram.py
* get_optimal_centers.py
* run_model.py

I've also taken a quick look at the code of the three python files, which do not seem to contain implementations of the four preprocessing steps. For example, I tried to search for the keywords "erosion" and "dilation" but found nothing.

So my question is, how to perform the four preprocessing steps? Are they included in the GMIC scripts?
* If yes, does it mean I only have to use the code in README for DICOM-to-16bitPNG conversion and then replace the 16 images in samples_data/ and run the GMIC docker?  I've actully this but ended up with an output predictions.csv which contained very low probability values for both benign_pred and malignant_pred.
* If no, does it mean I have to write my own code to carry out the four preprocessing steps?

Thank you.

**Comment by chledowski** [comment]
Hi!

The steps are already included in the script [predict.sh](https://github.com/nyukat/mammography_metarepository/blob/master/models/nyu_gmic/predict/predict.sh):
- [crop_mammogram.py](https://github.com/nyukat/GMIC/blob/master/src/cropping/crop_mammogram.py) finds the largest connected components and performs erosion & dilation
- Flipping the image happens during data loading during [run_model.py](https://github.com/nyukat/GMIC/blob/master/src/scripts/run_model.py#L154)
- Resizing also happens during data loading, [here](https://github.com/nyukat/GMIC/blob/3e278997293262f03471f913c9344a4181592dd5/src/data_loading/loading.py#L72)


About your results, if the values of mal/ben for mal/ben cases are low, but still higher than the other values, then the model still would be able to distinguish between the cases. Maybe this is the case for you? What AUROC are you getting?
