### ISSUE TITLE
FRCNN_CAD

### ISSUE THREAD

**Issue by GuillaumeP2705** [nyukat/mammography_metarepository#29]
Hi
I am trying to reproduce the Ribli' work to obtain results similar with the INbreast' Sub-Dataset (0.969 breast-wise AUC from the table. 2), but without success (i got 0.93 breast-wise AUC).
In "Ribli, D., Horváth, A., Unger, Z., Pollner, P., & Csabai, I. (2018). Detecting and classifying lesions in mammograms with Deep Learning. Scientific Reports, 8(1), 4165. https://doi.org/10.1038/s41598-018-22437-z", they exclude 8 exams without specifying which one. 
Did you remove some specific exam from the INbreast Sub-Dataset to obtain your 0.969 AUC breast-wise ?

Thanks a lot for your help,

**Comment by jwitos** [comment]
Hi @GuillaumeP2705, we used a subset of INbreast exams in the same way as it was used in [Shen et al. 2019](https://www.nature.com/articles/s41598-019-48995-4) (the end2end) paper. 

If you would like to reproduce our results on INbreast dataset, please take a look at Supplementary Table 2 [in our pre-print](https://arxiv.org/pdf/2108.04800.pdf), which lists all image names that were used to evaluate the INbreast dataset.

**Comment by GuillaumeP2705** [comment]
Hi Thanks 
I found my answer in the the fastRCNN' code. Thanks for your help
