### ISSUE TITLE
Question Regarding score.py

### ISSUE THREAD

**Issue by KiLJ4EdeN** [nyukat/mammography_metarepository#31]
Hello, first off thanks for the great and inspiring work.
I tried inference with the GMIC model on inbreast dataset. the results on image level were an AUC of 80.
but i noticed that score.py is only calculating AUC using malignant predictions and labels. Changing the score.py to calculate metrics for benign predictions only results in an AUC of 43. Do we need the benign labels for the calculation of AUC as well or it's not required for reporting metrics.

**Comment by jwitos** [comment]
Hi @KiLJ4EdeN. I'm not sure what you mean by benign AUC being "required for reporting metrics". In our paper and repository, we did not calculate performance for the classification of benign lesions. We only investigated models that predict whether breast cancer is present in the screening mammogram. This is the most common use case, and all models were trained & optimized for identifying exams with breast cancer, not benign findings, so the performance for the latter would be worse.

**Comment by KiLJ4EdeN** [comment]
> Hi @KiLJ4EdeN. I'm not sure what you mean by benign AUC being "required for reporting metrics". In our paper and repository, we did not calculate performance for the classification of benign lesions. We only investigated models that predict whether breast cancer is present in the screening mammogram. This is the most common use case, and all models were trained & optimized for identifying exams with breast cancer, not benign findings, so the performance for the latter would be worse.

Thank you. I feel like i phrased my question badly but that does answer my question and i will close the issue now.
